### ISSUE TITLE
Make "festival" drop-down navbar item

### ISSUE THREAD

**Issue by Aariq** [resbazaz/website#102]
Instead of a bunch of links at the bottom of the "Events" page, have a navbar item "Festivals" or "Past Festivals" that is a drop-down.  There are examples here: https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation

**Comment by Aariq** [comment]
Something like this:

```yaml
website:
  title: "ResBaz Arizona"
  navbar:
    background: dark
    foreground: primary
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd#events
        text: Events
      - sidebar:festivals

  sidebar:
    - id: festivals
      title: "Festivals"
      style: "docked" #not sure if necessary
      collapse-level: 2 #not sure if necessary
      contents: 
        - "resbaz/*.qmd" #not totally sure this works

```
